#!/bin/sh

#
#Desktop Use
#

#Terminal
super + Return
	alacritty

#screenshot
Print
	flameshot gui
	
#Close Window
super + shift q
	bspc node -c

#Launch Rofi
super + s
	rofi -show drun

#Open Thunar
super + e
	thunar

	
# reload sxhkd configuration file
super + shift + s
	pkill -USR1 -x sxhkd ;\
	notify-send "sxhkd: sxhkd has been restarted."

#Workspaces
super + {1-5}
	bspc desktop -f ^{1-5}

#Swap node focus
super + {h,j,k,l}
	bspc node -f {west,south,north,east}

#Swap node
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}


#
#Window Options
#

#Set Window State
super + {t,shift + t,space,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#Move Floating Window
ctrl + alt + {Left, Down, Up, Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Move window to next workspace
super + shift + Right
	bspc node -d next.local --follow

#Move window to previous workspace
super + shift + Left 
	bspc node -d prev.local --follow

## resize

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

#Rotate window horizontal/Vertical ClockWise
super + shift + v
	bspc node @parent --rotate 90


#
#Volume/Audio
#

#Raise Volume
XF86AudioRaiseVolume
	/usr/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

#Lower Volume
XF86AudioLowerVolume
	/usr/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

#Mute Volume
XF86AudioMute
	/usr/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle



#
#Brightness
#

XF86MonBrightness{Up,Down}  
  brightnessctl s 250{+,-}
